# Generated by Django 6.0.5 on 2026-06-08 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('attack', '공격'), ('action', '행동'), ('enhance', '강화'), ('special', '필살기')], max_length=20)),
                ('cost', models.IntegerField(default=0)),
                ('effect', models.TextField(blank=True)),
                ('card_img_url', models.URLField(blank=True)),
                ('include_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '카드',
                'ordering': ['idol', 'card_id'],
            },
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('leader_gimmick', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('ban_count', models.IntegerField(default=0)),
                ('banner_img_url', models.URLField(blank=True)),
                ('icon_img_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': '아이돌',
                'ordering': ['idol_id'],
            },
        ),
        migrations.CreateModel(
            name='DuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tts', 'Table Top Simulator'), ('manual', '수동 입력')], default='tts', max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('player1_name', models.CharField(max_length=50)),
                ('player2_name', models.CharField(max_length=50)),
                ('winner', models.IntegerField(choices=[(0, '무'), (1, 'P1'), (2, 'P2')], default=0)),
                ('p1_deck_code', models.CharField(blank=True, max_length=500)),
                ('p2_deck_code', models.CharField(blank=True, max_length=500)),
                ('player1_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_duels', to=settings.AUTH_USER_MODEL)),
                ('player2_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_duels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '대전 기록',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='DuelCardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(choices=[(1, 'P1'), (2, 'P2')])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.card')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_slots', to='api.duelrecord')),
            ],
            options={
                'verbose_name': '대전 카드 슬롯',
            },
        ),
        migrations.CreateModel(
            name='DuelIdolSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(choices=[(1, 'P1'), (2, 'P2')])),
                ('slot_type', models.CharField(choices=[('pick', '픽'), ('ban', '밴')], max_length=10)),
                ('is_leader', models.BooleanField(default=False)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idol_slots', to='api.duelrecord')),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idol')),
            ],
            options={
                'verbose_name': '대전 아이돌 슬롯',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='idol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.idol'),
        ),
        migrations.CreateModel(
            name='PlayerDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deck_code', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('cards', models.ManyToManyField(blank=True, to='api.card')),
                ('idol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.idol')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '플레이어 덱',
                'ordering': ['-updated_at'],
            },
        ),
    ]
