# Generated by Django 6.0.5 on 2026-06-09 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_level',
            field=models.IntegerField(choices=[(1, 'P.1'), (2, 'P.2'), (3, 'P.3')], default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='voltage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerdeck',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='playerdeck',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeckComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_comments', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.playerdeck')),
            ],
            options={
                'verbose_name': '덱 코멘트',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField(blank=True)),
                ('card_img_url', models.URLField(blank=True)),
                ('idol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_cards', to='api.idol')),
            ],
            options={
                'verbose_name': '메모리 카드',
                'ordering': ['memory_id'],
            },
        ),
        migrations.AddField(
            model_name='playerdeck',
            name='memory_cards',
            field=models.ManyToManyField(blank=True, to='api.memorycard'),
        ),
        migrations.CreateModel(
            name='DeckLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.playerdeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '덱 추천',
                'unique_together': {('deck', 'user')},
            },
        ),
    ]
