# Generated by Django 6.0.5 on 2026-06-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_card_level_card_voltage_playerdeck_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['idol', 'card_id'], 'verbose_name': '카드', 'verbose_name_plural': '카드'},
        ),
        migrations.AlterModelOptions(
            name='deckcomment',
            options={'ordering': ['created_at'], 'verbose_name': '덱 코멘트', 'verbose_name_plural': '덱 코멘트'},
        ),
        migrations.AlterModelOptions(
            name='decklike',
            options={'verbose_name': '덱 추천', 'verbose_name_plural': '덱 추천'},
        ),
        migrations.AlterModelOptions(
            name='idol',
            options={'ordering': ['idol_id'], 'verbose_name': '아이돌', 'verbose_name_plural': '아이돌'},
        ),
        migrations.AlterModelOptions(
            name='memorycard',
            options={'ordering': ['memory_id'], 'verbose_name': '메모리 카드', 'verbose_name_plural': '메모리 카드'},
        ),
        migrations.AlterModelOptions(
            name='playerdeck',
            options={'ordering': ['-updated_at'], 'verbose_name': '플레이어 덱', 'verbose_name_plural': '플레이어 덱'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cost',
        ),
    ]
