# Generated by Django 6.0.5 on 2026-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_card_options_alter_deckcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fan_addition',
            field=models.IntegerField(default=0),
        ),
    ]
