# Generated by Django 6.0.5 on 2026-06-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_card_fan_addition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='ban_count',
        ),
    ]
