# Generated by Django 6.0.5 on 2026-06-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_idol_ban_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='start_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idol',
            name='start_vol',
            field=models.IntegerField(default=0),
        ),
    ]
