# Generated by Django 6.0.5 on 2026-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_idol_start_hand_idol_start_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdeck',
            name='card_list_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
