# Generated by Django 6.0.5 on 2026-06-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_playerdeck_card_list_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdeck',
            name='idol_ids_json',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
